name: fleetime_genshin
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  awesome_flutter_extensions: ^1.1.1
  cached_network_image: ^3.2.3
  dartz: ^0.10.1
  dio: ^5.2.1
  flex_color_scheme: ^7.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  go_router: ^8.0.1
  logger: ^1.4.0
  mockito: ^5.4.2
  responsive_framework: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
